# Generated by Django 5.1.4 on 2025-06-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='post_code',
            new_name='postcode',
        ),
    ]
