# Generated by Django 5.1.4 on 2025-06-18 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_rename_post_code_site_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='postcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_postcode', message='Invalid UK postcode.', regex='^[A-Z]{1,2}[0-9R][0-9A-Z]?\\s?[0-9][A-Z]{2}$')]),
        ),
    ]
