# Generated by Django 5.1.4 on 2025-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
    ]
