# Generated by Django 5.1.4 on 2025-06-24 10:22

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), geography=True, srid=4326),
        ),
    ]
