# Generated by Django 5.1.4 on 2025-06-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_site_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='location',
            new_name='coordinates',
        ),
    ]
