# Generated by Django 5.2.3 on 2025-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='account_type',
            field=models.CharField(default='base', max_length=255),
        ),
    ]
