# Generated by Django 5.2.3 on 2025-06-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_postcode',
            field=models.CharField(max_length=10),
        ),
    ]
