# Generated by Django 5.2.3 on 2025-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_id_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
