# Generated by Django 5.2.5 on 2025-08-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_alert_radius_user_distance_alerts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
