# Generated by Django 5.2.5 on 2025-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
