# Generated by Django 5.2.5 on 2025-08-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_search_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alert_radius',
            field=models.IntegerField(default=0),
        ),
    ]
